[JENKINS-67507] Artifacts deployed by direct invocation of deploy-file goal don't trigger downstream builds
jenkinsci/pipeline-maven-plugin pull request #398
Opened 2022-01-04 13:22 UTC by Schleuse

Adds a new `ExecutionHandler` for the `JenkinsMavenEventSpy` wich checks if the `MojoExecution` of the goal `org.apache.maven.plugins:maven-deploy-plugin:deploy-file` contains a lifecycle. When no lifecycle is present it assumes the `deploy`-Lifecycle.

https://issues.jenkins.io/browse/JENKINS-67507

2022-01-04 17:30 UTC, bguerin requested changes
please add unit tests for the newly added class

2022-01-04 21:33 UTC, Schleuse commented
I've created some tests. I wasn't sure if the tests should target the EventSpy or the handler directly. I have opted for the latter for now

2022-01-09 19:32 UTC, bguerin commented
Hello,
Sorry for the delay
Could you merge my personal branch on yours please :
https://github.com/bguerin/pipeline-maven-plugin/tree/trigger-downstream-of-deploy-file
I add an integration test to ensure your use case works and I would like to have it in that pull request

2022-01-09 22:15 UTC, Schleuse commented
Thanks for adding the integration tests, I've merge your branch onto mine 👍🏻

2022-01-09 22:23 UTC, bguerin approved these changes

2022-01-09 23:16 UTC, merged